language: node_js
node_js:
  - "node"
  - "10"
  - "8"

cache:
  directoreis:
    - $HOME/.npm

before_install:
  - npm install --global npm@latest
  - npm --version

install:
  - npx lerna bootstrap --ci

script:
  - npx lerna run test

notifications:
  webhooks: "https://www.travisbuddy.com/"
