language: node_js

node_js:
  - "12"
  - "10"
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm install --global npm@latest
  - npm --version

install:
  # no ci because this is library code
  - npx lerna bootstrap --no-ci

script:
  - npx lerna run test

notifications:
  webhooks: "https://www.travisbuddy.com/"
