language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"

cache:
  directoreis:
  - $HOME/.npm

before_install:
  - npm install --global npm@latest
  - npm --version
  - npm install --global lerna

install:
  - lerna bootstrap

script:
  - lerna run test

notifications:
  webhooks: "https://www.travisbuddy.com/"

